import { Shield } from "lucide-react";

const Privacy = () => (
  <div className="min-h-screen bg-background">
    <div className="max-w-3xl mx-auto px-6 py-10">
      <div className="flex items-center gap-3 mb-8">
        <Shield className="w-6 h-6 text-primary" />
        <h1 className="text-2xl font-bold text-foreground">Privacy Policy</h1>
      </div>

      <article className="prose prose-sm dark:prose-invert max-w-none space-y-6 text-sm text-foreground leading-relaxed">
        <p className="text-muted-foreground">
          Last updated: {new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" })}
        </p>

        <section>
          <h2 className="text-base font-semibold uppercase tracking-wide mt-6">1. Who we are</h2>
          <p>
            Made for ATS ("we", "us") is a CV optimisation toolkit built for SKEMA Business School
            students and EU professionals. We operate this site at https://ohmyats.lovable.app.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold uppercase tracking-wide mt-6">2. What we collect</h2>
          <ul className="list-disc list-inside space-y-1">
            <li><strong>CV text</strong> you upload or paste, and <strong>job description text</strong> you provide.</li>
            <li><strong>Scan results</strong> generated by our AI models (scores, feedback, rewrites).</li>
            <li><strong>Account email</strong> if you choose to sign up.</li>
            <li><strong>Job tracker, contacts, notes, and CV versions</strong> you save.</li>
            <li>We do not use third-party analytics or advertising trackers.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold uppercase tracking-wide mt-6">3. Legal basis (GDPR Art. 6)</h2>
          <ul className="list-disc list-inside space-y-1">
            <li><strong>Consent</strong> — for storing your CV history and account data.</li>
            <li><strong>Contract</strong> — to deliver the ATS scanning service you requested.</li>
            <li><strong>Legitimate interest</strong> — for service security and abuse prevention.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold uppercase tracking-wide mt-6">4. AI sub-processors</h2>
          <p>
            CV and JD text is sent in real time to large language models hosted by Google (Gemini)
            and OpenAI (GPT) via the Lovable AI Gateway. Inputs are processed for the duration of
            the request only — providers do not retain prompts for training under our gateway
            configuration.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold uppercase tracking-wide mt-6">5. Retention</h2>
          <ul className="list-disc list-inside space-y-1">
            <li>Unsigned scans are not persisted server-side after the response is returned.</li>
            <li>Saved scan history is kept for <strong>90 days</strong> then automatically purged.</li>
            <li>CV versions you explicitly save are kept until you delete them or your account.</li>
            <li>Account data is deleted within 30 days of an account-deletion request.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold uppercase tracking-wide mt-6">6. Your rights</h2>
          <p>Under the GDPR you have the right to:</p>
          <ul className="list-disc list-inside space-y-1">
            <li><strong>Access</strong> — download all your data as JSON from your Profile page.</li>
            <li><strong>Erasure</strong> — delete your account and all linked data from your Profile page.</li>
            <li><strong>Portability</strong> — the export is structured and machine-readable.</li>
            <li><strong>Rectification</strong> — edit or remove any saved scan, contact, or note.</li>
            <li><strong>Object / withdraw consent</strong> — by deleting your account.</li>
            <li><strong>Lodge a complaint</strong> with your national data protection authority (e.g. CNIL in France).</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold uppercase tracking-wide mt-6">7. Security</h2>
          <p>
            Data is stored in the EU on Supabase infrastructure with row-level security so users
            can only access their own rows. Passwords are checked against the Have I Been Pwned
            database to block known-leaked credentials. All traffic is encrypted in transit (TLS).
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold uppercase tracking-wide mt-6">8. Cookies</h2>
          <p>
            We use only strictly necessary cookies (session, theme preference). No tracking or
            advertising cookies are set.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold uppercase tracking-wide mt-6">9. Contact</h2>
          <p>
            For any privacy request or to exercise the rights above, email
            <a href="mailto:privacy@ohmyats.app" className="text-primary underline ml-1">privacy@ohmyats.app</a>.
          </p>
        </section>
      </article>
    </div>
  </div>
);

export default Privacy;
